### ISSUE TITLE
checking for user service (JWT)

### ISSUE THREAD

**Issue by keesee** [kalisio/feathers-distributed#10]
This is an interesting project!  Thanks for dreaming it up!  
Played around with it and can't seem to get distributed jwt authentication to work. 
```
Error: options.service does not exist.
        Make sure you are passing a valid service path or service instance and it
is initialized before @feathersjs/authentication-jwt.
    at new JWTVerifier (M:\mynyn\node_modules\@feathersjs\authentication-jwt\lib\verifier.js:11:13)
```
after digging in, it seems that feathers authJWT doesn't like that the users service isn't available on init.   
I added the following to app.js just before returning app. 
```js
  const getMessages = () => console.log(Object.keys(app.services))
  setInterval(getMessages, 1000);

```
it does eventually add the users service, but after several seconds.  As such, I can only enable authentication on a users instance where app.use(users, .....) is internal and already there.  

Have I missed something? Assuming its a simple fix given documentation suggests this is possible?

my authentication plugin is pretty standard
```js
module.exports = function (app) {
    app.configure(auth(options))
    app.configure(authenticationJwt({service: 'users'}));
    app.configure(authenticationLocal());
}
```

**Comment by claustres** [comment]
Hello, thanks for your interest in this project. Could you provide us with a more detailed and complete setup of your app as well as main module versions (Feathers, etc.) ?

**Comment by keesee** [comment]
the repo and commit where I tested it can be found below.   The commit has a few github comment in it for you to see the relevant additions :)

I used Florian Fiedler's feathers v3 fork as a base, but was having the same issue on v2.  

after playing around a bit ore I found the following in all of the feathers auth verifiers

```js

class JWTVerifier {
  constructor (app, options = {}) {
    this.app = app;
    this.options = options;
    this.service = typeof options.service === 'string' ? app.service(options.service) : options.service;

    if (!this.service) {
      throw new Error(`options.service does not exist.\n\tMake sure you are passing a valid service path or service instance and it is initialized before @feathersjs/authentication-jwt.`);
    }

.....

```

if (!this.service) { ... seems to be the problem?  Feathers assumes that the service will Always be there.  forking feathers-auth-jwt and feathers-auth-local then removing that check works. 

**repo....**

https://github.com/keesee/test-fths-auth-v3/commit/d82026566f8dbb724e185206045e711d10ac1353

**Comment by claustres** [comment]
I still not had time to check the PR for Feathers v3 so I will have a look first next week probably then check your issue. 

What seems to me a little strange when I look at the code is that you modified the gateway example in order to add authentication on both: the gateway and the services. As recently added in the doc there are two different ways of adding auth: https://github.com/kalisio/feathers-distributed#authentication. In this specific case you should not add auth on the services otherwise it will result in some conflicting state. For the other use case please have a look at the [tests](https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js).

If you have to wait for a remote service to be initialized you should proceed as in [tests](https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js#L92) as well.

**Comment by keesee** [comment]
I checked out the new updates for v3 you published and dived a bit deeper into the code.   As I looked at your gateway, I noticed that the gateway node hosts the user service.  a few days days when I added authentication to the example services, I was specifically wanting to see if it worked in cases where auth and user weren't hosted on the same node. The main reason is that I don't feel the gateway should be forced to host accounts.  They may need to scale on their own and in some cases secured to a deeper extent.  You also don't want heavy load from traffic having any effect on the user and authoriztion response times for internal services that may also be referencing user data.

I've worked a bit on it and will continue next week.  My initial impression is that there may be some need for PR to feathers auth or a fork of the feathers auth modules.  distributed authentication work different enough from the feathers approach that slightly different authentication and authorization might be required either through a configuration flag or a distributed focused fork. 

just my initial thoughts.... look forward to hearing yours.   I wish I had more time to dive in full tilt now.  This is fun stuff :)

**Comment by claustres** [comment]
OK I now understand your point. Yes it is almost sure that feathers local auth module tries to immediately retrieve the user service (eg https://github.com/feathersjs/authentication-local/blob/master/lib/verifier.js#L12), and in the distributed case the local façade to the remote user service will only be available asynchronously. 

I don't know if the existing architecture of both feathers and feathers-distributed could support the initialization of the auth according to this. Maybe you can try something like this:
1. let microservice apps start
2. on the auth gateway simply initialize the app and the distribution plugin then wait for the user service to be remotely available
3. when available proceed on the auth gateway with auth config and local services creation if any

This could work if feathers allow to call `app.use(xxx)` before auth configuration has finished, indeed remote services will be automatically added to the gateway like this on discovery.

Don't have much time to test it now but let me know. I'm afraid adding some async config in feathers is a breaking change and will be hard to push (eg see a long discussion on a similar topic https://github.com/feathersjs/feathers/issues/509).

**Comment by keesee** [comment]
Yes, I agree.  introducing changes to feathers won't work.  ultimately, I think all we will need is some login in cote requesters that return not ready or not initialized and some custom verifiers.    We'll see.  I'll keep you updated.  Closing this issue for now since my question was answered.  Thanks again.

**Comment by keesee** [comment]
@claustres 
here is a really quick verifier I wrote.  based on standard one. 
I had a bit of time on a flight, so I hacked it together. 
it works if you can get the password from the user service.  we obviously don't want that.
the process needs to change a bit, but the verifier doesn't kill the app because the service is missing.
applying this logic to the JWT verifier should work, since there's not password comparison.  you just ensure the use is in the DB. For local auth, pass the credentials along and look for a 200 back. 

local authentication verifier.
```js
const Debug = require('debug');
const bcrypt = require('bcryptjs');
const get = require('lodash.get');
const omit = require('lodash.omit');

const debug = Debug('@feathersjs/authentication-local:verify');

class LocalVerifier {
  constructor (app, options = {}) {
    this.app      = app;
    this.active   = false
    this.options  = options;
    this.service  = typeof options.service === 'string' ? app.service(options.service) : options.service;
    this.counter   = 0      // times we've checked for the user service to be there
    this.seeking   = true   // checking for users service.  haven't given up yet
    this.times     = 30     // number of times we need to check.  ( default 30 times, 2 second intervals = 1 minute  )
    this.interval  = 2000   // milliseconds between tries.


    // Recursive fucntion that waits for the users service.
    const findSetupService = () => {
      // check if the service is there
      if (!this.service) {
        // if the service isn't there start waiting.
        if ( !Object.keys(app.services).includes(options.service)) {
          // service isn't there. increment counter, wait internal, try again
          if (this.counter < this.times) {
            // times not exceeded try again
            this.counter = this.counter + 1
            setTimeout(() => startVertifier(), this.interval)
          } else {
            // times exceeded throw error
            this.seeking = false
            throw new Error('user service not available.');
          }
        } else {
          // service found.  set it up.
          this.service      = typeof options.service === 'string' ? app.service(options.service) : options.service;
          // sevice _id field required.
          // adding it here, but there must be a better way.
          // this will only work for mongo
          this.service.id   = '_id'
          this.active       = true
          this.seeking      = false
        }
      }
    }
    // run the find and setup service function
    findSetupService()

    // commented out.  should assume the service will be there.
    // if (!this.service) {
    //   throw new Error(`options.service does not exist.\n\tMake sure you are passing a valid service path or service instance and it is initialized before @feathersjs/authentication-local.`);
    // }

    this._comparePassword = this._comparePassword.bind(this);
    this._normalizeResult = this._normalizeResult.bind(this);
    this.verify = this.verify.bind(this);
  }

  _comparePassword (entity, password) {
    // select entity password field - take entityPasswordField over passwordField
    const passwordField = this.options.entityPasswordField || this.options.passwordField;

    // find password in entity, this allows for dot notation
    const hash = get(entity, passwordField);

    if (!hash) {
      return Promise.reject(new Error(`'${this.options.entity}' record in the database is missing a '${passwordField}'`));
    }

    debug('Verifying password');

    return new Promise((resolve, reject) => {
      bcrypt.compare(password, hash, function (error, result) {
        // Handle 500 server error.
        if (error) {
          return reject(error);
        }

        if (!result) {
          debug('Password incorrect');
          return reject(false); // eslint-disable-line
        }

        debug('Password correct');
        return resolve(entity);
      });
    });
  }

  _normalizeResult (results) {
    // Paginated services return the array of results in the data attribute.
    let entities = results.data ? results.data : results;
    let entity = entities[0];

    // Handle bad username.
    if (!entity) {
      return Promise.reject(false); // eslint-disable-line
    }

    debug(`${this.options.entity} found`);
    return Promise.resolve(entity);
  }

  verify (req, username, password, done) {

    if (this.active) {
      debug('Checking credentials', username, password);
      const id = this.service.id;
      const usernameField = this.options.entityUsernameField || this.options.usernameField;
      const params = Object.assign({
        'query': {
          [usernameField]: username,
          '$limit': 1
        }
      }, omit(req.params, 'query', 'provider', 'headers', 'session', 'cookies'));

      if (id === null || id === undefined) {
        debug('failed: the service.id was not set');
        return done(new Error('the `id` property must be set on the entity service for authentication'));
      }

      // Look up the entity
      this.service.find(params)
        .then(response => {
          const results = response.data || response;
          if (!results.length) {
            debug(`a record with ${usernameField} of '${username}' did not exist`);
          }
          return this._normalizeResult(response);
        })
        .then(entity => this._comparePassword(entity, password))
        .then(entity => {
          const id = entity[this.service.id];
          const payload = { [`${this.options.entity}Id`]: id };
          done(null, entity, payload);
        })
        .catch(error => error ? done(error) : done(null, error, { message: 'Invalid login' }));
    } else {
      if (this.seeking) {
        // if still seeking for the service, throw appropiate error
        return ({ error: true, message: this.options.service + ' is not ready yet' });
      } else {
        // exhausted seeking tries, so throw unavailable error.
        return ({ error: true, message: this.options.service + ' is not unavailable' });
      }
    }
  }
}

module.exports = LocalVerifier;

```
