### ISSUE TITLE
Support for Feathers 5 with koa middleware

### ISSUE THREAD

**Issue by nathanbrizzee-cdcr** [kalisio/feathers-distributed#108]
### Steps to reproduce

Create a new application with the Feathers 5 (currently 5.0.0-pre.31) generator and choose the defaults but specifically choose these -> (KOA) (JAVASCRIPT)
Note: When I chose TypeScript, I couldn't get past the typescript errors so I went back and used JavaScript.

```
npx @feathersjs/cli@pre generate app
```

Add feathers-distributed according to the documentation page:
app.js
```js
import feathersDistribution from '@kalisio/feathers-distributed'
...
app.configure(
  feathersDistribution({
    hooks: {
      before: {
        all: [
          // authenticate('jwt'),
        ]
      }
    },
    services: (service) => true,
    remoteServices: (service) => true
  })
)
export { app }

```
Then try to run the application with 
```
npm run dev
```

### Expected behavior
The application should run like it does with ExpressJS

### Actual behavior
Application crashes with the following output:
```
> server@0.0.0 dev
> nodemon src/

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/`
warn: Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
/home/user/code/feathers5-2/server/node_modules/@feathersjs/feathers/lib/service.js:55
        throw new Error(`Invalid service object passed for path \`${location}\``);
              ^

Error: Invalid service object passed for path `distribution/healthcheck/:key?`
    at wrapService (/home/user/code/feathers5-2/server/node_modules/@feathersjs/feathers/lib/service.js:55:15)
    at Feathers.use (/home/user/code/feathers5-2/server/node_modules/@feathersjs/feathers/lib/application.js:107:56)
    at Feathers.use (/home/user/code/feathers5-2/server/node_modules/@feathersjs/koa/lib/index.js:48:36)
    at Feathers.<anonymous> (file:///home/user/code/feathers5-2/server/node_modules/@kalisio/feathers-distributed/lib/index.js:385:9)
    at Feathers.configure (/home/user/code/feathers5-2/server/node_modules/@feathersjs/feathers/lib/application.js:37:18)
    at file:///home/user/code/feathers5-2/server/src/app.js:59:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
[nodemon] app crashed - waiting for file changes before starting...
```

I've debugged through the feathers-distributed code to the error points, but I don't know how to fix them.

### System configuration
**Module versions** (especially the part that's not working):
package.json
```json
  "dependencies": {
    "@feathersjs/authentication": "^5.0.0-pre.31",
    "@feathersjs/authentication-local": "^5.0.0-pre.31",
    "@feathersjs/authentication-oauth": "^5.0.0-pre.31",
    "@feathersjs/configuration": "^5.0.0-pre.31",
    "@feathersjs/errors": "^5.0.0-pre.31",
    "@feathersjs/feathers": "^5.0.0-pre.31",
    "@feathersjs/koa": "^5.0.0-pre.31",
    "@feathersjs/mongodb": "^5.0.0-pre.31",
    "@feathersjs/schema": "^5.0.0-pre.31",
    "@feathersjs/socketio": "^5.0.0-pre.31",
    "@feathersjs/transport-commons": "^5.0.0-pre.31",
    "@feathersjs/typebox": "^5.0.0-pre.31",
    "@kalisio/feathers-distributed": "^2.0.2",
    "koa-static": "^5.0.0",
    "mongodb": "^4.11.0",
    "winston": "^3.8.2"
  },
  "devDependencies": {
    "@feathersjs/authentication-client": "^5.0.0-pre.31",
    "@feathersjs/cli": "^5.0.0-pre.31",
    "@feathersjs/rest-client": "^5.0.0-pre.31",
    "axios": "^0.27.2",
    "cross-env": "^7.0.3",
    "mocha": "^10.1.0",
    "nodemon": "^2.0.20",
    "prettier": "^2.7.1"
  }
```

**NodeJS version**: v16.15.1 

**NPM version**: 8.11.0

**Operating System**: Ubuntu 22.04.1 LTS

**Browser Version**: n/a

**React Native Version**: n/a
 
**Module Loader**: n/a

**Comment by jchamb** [comment]
@claustres feathers-swaggers working branch for v5 has some test helpers. https://github.com/feathersjs-ecosystem/feathers-swagger/blob/custom-methods-v5/lib/helpers.js

**Comment by claustres** [comment]
Thanks @jchamb, by the way to you have any example on how to declare a similar route with Koa ?

**Comment by jchamb** [comment]
I'm not familiar with internals of this package at all. I actually just saw this as I was checking to see if ya'll had v5 support while digging around some options for micro service discovery.

If you are just asking how to declare routes in koa, koa doesn't have the `get` and other helpers like express unless you register https://github.com/koajs/router. I haven't had time to look at feathers koa adapter yet to see what they are doing either so don't know if thats part of the adapter middleware or not. You can do really basic route additions though doing something like the below. 

```
app.use(async (ctx, next) => {
        if (ctx.url === 'something') {
          ctx.body = 'Sweet';
        }
        return next();
      });
```

feathers-swagger is basically just doing that, with their conditionals.

Note I don't maintain/contribute to feathers-swagger either. I just knew that existed as I was playing with v5 and testing our dependencies will upgrade smoothly. Maybe their core contributor [Mairu](https://github.com/Mairu) would have better advice for you.

**Comment by nathanbrizzee-cdcr** [comment]
@claustres, I have an update to my last comment.  I saw your refactor check-in so I thought I would try it.  I updated my package.json to this:
```
    "@kalisio/feathers-distributed": "kalisio/feathers-distributed#master",
```
I tried running the app again and this time it started up.  Hurray!!  So I created a second V5 application exactly the same but changed its startup port to 3031.  I added a service to each application with different names and started both of them.  They both PUB/SUB with each other.  Another hurray!
I tried calling a service in the first server via Postman on it's port number (3030). Hurray, It works.  Then I tried calling the remote service in the second server (port 3031) but from the first server's port (3030).  This one works too!
So initial testing is showing that your code changes make feathers-distributed work with koa now.  We just don't have the healthcheck api end point but that can come later.  The good news is that there is a fix for Feathers V5 and koa.  Thanks for such prompt work on this library.  I can't wait for it to be released officially!  It probably needs some more testing just to make sure.

**Comment by daffl** [comment]
I don't believe there is anything Express specific here other than the Healthcheck which I don't see a reason why it couldn't be a normal service like this:

```js
const healthcheckRoute = (options.healthcheckPath || '/distribution/healthcheck/') + ':key'
debug('Initializing feathers-distributed healthcheck route', healthcheckRoute)
app.use(healthcheckRoute, {
  async find (params) {
    const key = params.route.key || 'default'
    // Not yet registered
    if (!app.serviceRequesters[key]) {
      throw new NotFound(`No app registered with key ${key}`)
    }

    return healthcheck(app, key)
  }
})
```

**Comment by claustres** [comment]
Thanks @nathanbrizzee-cdcr for testing, great to know it works fine. I would like to make healthcheck available in Koa before releasing though. 

Thanks @daffl for your proposal, as always relevant. I am not used to register a service when I only need a get route but now I realize I did it wrong because doing this will allow to support multiple middlewares. I will try to update this soon in the code, but making an additional test with koa will require more effort.

**Comment by claustres** [comment]
@nathanbrizzee-cdcr Could give it a try on the master bracnh ? The healthcheck should work with koa based on the suggestion from @daffl, Thanks.

**Comment by nathanbrizzee-cdcr** [comment]
Hi @claustres , I was able to test the distribution links.  I guess I didn't understand how they worked before but I have a better understanding now.
I had to change my package.json to the following to get your latest check-in
```json
    "@kalisio/feathers-distributed": "kalisio/feathers-distributed#80299d0a639fa4d32b287df051519b9ab5c4f2c3",
```

When I call the distribution link for the remote server key thru the gateway address
```
localhost:3030/distribution/healthcheck/ms-1
```
I get a list of services in the remote server.
```json
{
    "api/v1/anotherms-1": true,
    "api/v1/ms-1": true
}
```
And when I call the healthcheck end point for the gateway key from the remote server address, I get the services in the gatway
```
localhost:3031/distribution/healthcheck/gateway
```
```json
{
    "api/v1/gs-1": true
}
```

If I try calling the healthcheck api with the key of the server I am connecting to, I get a service not found.  I guess that makes sense but I wasn't expecting it.

```
localhost:3030/distribution/healthcheck/gateway
```
```json
{
    "name": "NotFound",
    "message": "No app registered with key gateway",
    "code": 404,
    "className": "not-found"
}
```
It would be really cool if I could call a distribution healthcheck link on a gateway and get a list of all services that have been registered without asking specifically for the key.  That would help to see the status of all services in real time.
Thanks so much for getting this code updated!!!

**Comment by claustres** [comment]
@nathanbrizzee-cdcr Good idea to add a global healthcheck endpoint now available using the app distribution key or without any key: https://github.com/kalisio/feathers-distributed/issues/109.

I think the Koa middleware could be registered similarly than the expresse one:
```
import { errorHandler } from '@feathersjs/koa'
feathersDistribution({
  middlewares: {
     after: errorHandler()
  }
})
```

**Comment by nathanbrizzee-cdcr** [comment]
Thanks so much @claustres . I tested the new healthcheck and it works great.  I'll try your suggestion for the errorHandler. I don't know why I didn't think of it but it makes sense the way you showed it.  Guess I was thinking too hard. :-)
