### ISSUE TITLE
Dove Health Check Crashing app.

### ISSUE THREAD

**Issue by jchamb** [kalisio/feathers-distributed#110]
### Steps to reproduce

1. Generate a fresh app using the CLI
2. Add feathers distributed `npm install @kalisio/feathers-distributed --save`
3. add basic config after adapters

```js
import distributed from '@kalisio/feathers-distributed'

...
// Configure services and transports
app.configure(rest())
app.configure(
  socketio({
    cors: {
      origin: app.get('origins')
    }
  })
)

// add distributed
app.configure(distributed()) 

app.configure(sqlite)
...
```

5. Start App `npm run dev`

Error output
```

> distributed@0.0.0 dev
> nodemon src/

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/`
/Users/jakechamberlain/Sites/distributed/node_modules/@feathersjs/feathers/lib/service.js:55
        throw new Error(`Invalid service object passed for path \`${location}\``);
              ^

Error: Invalid service object passed for path `distribution/healthcheck/:key?`
    at wrapService (/Users/jakechamberlain/Sites/distributed/node_modules/@feathersjs/feathers/lib/service.js:55:15)
    at Feathers.use (/Users/jakechamberlain/Sites/distributed/node_modules/@feathersjs/feathers/lib/application.js:107:56)
    at Feathers.use (/Users/jakechamberlain/Sites/distributed/node_modules/@feathersjs/koa/lib/index.js:50:36)
    at Feathers.<anonymous> (file:///Users/jakechamberlain/Sites/distributed/node_modules/@kalisio/feathers-distributed/lib/index.js:385:9)
    at Feathers.configure (/Users/jakechamberlain/Sites/distributed/node_modules/@feathersjs/feathers/lib/application.js:37:18)
    at file:///Users/jakechamberlain/Sites/distributed/src/app.js:37:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)

Node.js v18.11.0
[nodemon] app crashed - waiting for file changes before starting...
```

I confirm that simplify commenting out the whole health check registration inside of node_modules package makes the error go away.

### System configuration

**Module versions** (especially the part that's not working):

```
"@feathersjs/feathers": "^5.0.0-pre.33",
 "@kalisio/feathers-distributed": "^2.0.2",
```

**NodeJS version**: `Node.js v18.11.0`
**Operating System**: `OSX 13.0`

**Comment by jchamb** [comment]
I dug a bit deeper here and realized master branch did not 2.0.2. I switched my import to `"@kalisio/feathers-distributed": "kalisio/feathers-distributed#master"`

and everything was fine.

I'd recommend the read me file be updated to not include the 2.0.x
```
The [master](https://github.com/kalisio/feathers-distributed) branch and >= 2.0.x version is expected to work with [Feathers v5](https://dove.docs.feathersjs.com/) (a.k.a. Dove).
```

I had assumed that with it saying `>=2.0.x` current standard install would work fine with Dove now.

**Comment by claustres** [comment]
Dear @jchamb, for sure the 2.x version was made to work with Dove as it actually depends on Feathers 5.x dependencies. We are using it for months with Dove, like some other people. All the tests are running with a Feathers Dove application, like our example as well. So claiming it does not work with Dove in the README would actually be not true.

I suspect your issue be similar to https://github.com/kalisio/feathers-distributed/issues/108 and specifically linked to Koa. You are right we made a fix on the master branch for this issue but we were waiting for more feedback before releasing. However, as it seems to lead to confusion I will make a 2.1.0 release today.

**Comment by jchamb** [comment]
@claustres thanks for releasing. It was definitely koa specific which I remembered from the previous discussion and why I even went looking at the source. As I mention just generating a brand new app through cli with default options would crash any 2.0 version which is why I said it doesn't work. I was trying to be explicit since most users coming in would not have recognize 2.0.x meaning express based only.
