### ISSUE TITLE
Add support for Redis/Centralized Discovery

### ISSUE THREAD

**Issue by subodhpareek18** [kalisio/feathers-distributed#14]
As described by cote here:
https://github.com/dashersw/cote#using-centralized-discovery-tools
> cote is built to be zero-configuration, and relies on IP broadcast/multicast to work. However, as of 2017, cloud providers don't support this functionality out of the box. In these cases, one can use Docker Cloud and its Weave network integration. However, Docker Cloud may not be suitable for everyone, due to varying reasons.

Therefore cote also has support for redis and can be used like so:
```js
// As an environment variable:
COTE_DISCOVERY_REDIS_HOST=redis node service.js

// As part of cote's module configuration:
const cote = require('cote')({ redis: { host: 'redis' } });

// As part of each component's discovery configuration:
const cote = require('cote');
const req = new cote.Requester({ name: 'req' }, { redis: { host: 'redis' } });
```

It would be great if we could configure feathers-distibuted with an options object and internally this library would use it to intialize cote.
```js
// Server
app.configure(distribution({
  cote: { host: 'redis' }
}));
```

**Comment by claustres** [comment]
I never used cote with redis but as far as I understand the redis configuration can be given either with env variables or config options. This means that it should already work if you provide the right env variables, doesn't it ? If so what will be the advantage of using config options ?

**Comment by subodhpareek18** [comment]
Yes you are correct, this additional configuration along with the one for multicast/broadcast ip addresses can be supplied as environment variables. 

The advantage of using config options is simply it's a more feathers like solution. I use feathers-config and have json files for dev/stag/prod and would ideally like to consolidate all env variables that way, instead of using additional dotenv files.

**Comment by claustres** [comment]
OK so if we'd like to implement it we should provide the options each time we require cote or create a component, that's it ?

**Comment by subodhpareek18** [comment]
At the user level it's being supplied once when configuring feathers-distributed.
```js
const opts = {
  cote: { host: 'redis' },
  ...otherStuff
}

app.configure(distribution(opts));
```

And then for the library I think it makes sense to pass it on to cote wherever it's being imported in the file.

```js
// old
import cote from 'cote'

// new
import makeCote from 'cote'
const cote = makeCote(opts.cote)

// CommonJS version would've been
const cote = require('cote')(opts.cote);
```

**Comment by claustres** [comment]
It's not that simple, options are provided dynamically at module initialization by the Feathers app while import are static, the `opts.cote` you mention in your code is not available just after the import line.

I have to look a little bit about it, we probably need to store the cote config or instance in the Feathers app object so that when calling `setup()` services are also able to access the options.

**Comment by claustres** [comment]
Started something, could you check master to see if it works ? Thanks

It would be better to add a test using REDIS but it is actually more a cote related thing although this could help validate we integrate options correctly.

**Comment by claustres** [comment]
Any feedback ?

**Comment by subodhpareek18** [comment]
Hi, sorry for the delayed response. Looks good to me.
