### ISSUE TITLE
Cannot Read Error Message When Throwing Exception in Remote Service

### ISSUE THREAD

**Issue by diruuu** [kalisio/feathers-distributed#20]
### Steps to reproduce

Error message always undefined on gateway service if throwing error from remote service.

Tell us what should happen

error.message should not be undefined

**Comment by claustres** [comment]
Could you please provide more context or code sample ?

Indeed in our tests we ensure that errors coming from a remote service are correctly forwarded to the gateway https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js#L283.

**Comment by claustres** [comment]
Also tested in example here https://github.com/kalisio/feathers-distributed/blob/master/example/index.html#L16. Please reopen with more context if it persists.
