### ISSUE TITLE
Authentication management

### ISSUE THREAD

**Issue by claustres** [kalisio/feathers-distributed#4]
Pass tokens between microservices.

**Comment by subodhpareek18** [comment]
I had written a simple api key auth for myself using `passport-custom`, I'm sure whatever functionality you have in mind should be achievable with such a strategy.

Here is a bare minimum sample snippet. Something like this useful/insightful?
```js
import Strategy from 'passport-custom';

export default opts => {
  return function() {
    const verifier = (req, done) => {
      // taken from header, but could really be present anywhere in the req
      const token = req.headers[opts.header];

      //  went for a simple hardcoded set of keys, but could easily encrypt and store tokens for each service in a database like username and passwords
      const match = opts.allowedKeys.includes(token);
  
      // if matches then auth is successful, else fails
      const user = match ? 'api' : match;
      return done(null, user);
    };

    this.passport.use('apiKey', new Strategy(verifier));
  };
};
```
```js
    app.configure(auth({...}));
    app.configure(jwt());
    app.configure(local({...}));
    //  configure like any other standard strategy
    app.configure(apiKey({...}));
```
```js
// write a conditional hook and put it in global hooks
export const authenticate = () =>
  iff(
    every(isProvider('external')),
    iffElse(
      ctx => ctx.params.headers[server.auth.apiKey.header],
      auth.hooks.authenticate('apiKey'),
      auth.hooks.authenticate(server.auth.strategies)
    )
  );
```

**Comment by claustres** [comment]
Actually I was simply thinking of the API gateway use case where a single node performs authentication. In this case the gateway collect the JWT and should forward it to other nodes when forwarding service requests to ensure security. But your solution might help, not yet started to work on it.

**Comment by Flofie** [comment]
We had exactly the same issue. Until now we used a passport-custom module to authenticate with an upstream server. 

Something like this:

`
const Strategy = require('passport-custom')
const feathers = require('@feathersjs/feathers')
const rest = require('@feathersjs/rest-client')
const auth = require('@feathersjs/authentication-client')
const decode = require('jwt-decode')
const request = require('request')

export default function(opts: any) {
  return function(this: any) {
    const verifier = async (req: any, done: any) => {
      const accessToken = req.params.headers['authorization']
      if (!accessToken) {
        return done(null, false)
      }

      try {
        const payload = decode(accessToken)
        const client = feathers()
        client.configure(rest(opts.authUrl).request(request))
        
        const user = await client.service('users').get(
          payload.userId, { headers: { Authorization: accessToken } }
        )
        return done(
          null,
          user,
          user
            ? {
                userId: user.id
              }
            : undefined
        )
      } catch (e) {
        return done(null, false)
      }
    }`

**Comment by Flofie** [comment]
With your distributed module it got a whole lot easier. We now authenticate the user on the gateway.
Therefore I extented your library with this:

```javascript
// When a remote service is declared create the local proxy interface to it
    app.serviceSubscriber.on('service', serviceDescriptor => {
    ...
      // registering hook object on every remote service
      if (distributionOptions.hooks) {
        app.service(serviceDescriptor.path).hooks(distributionOptions.hooks);
      }
      debug('Registered hooks on remote service on path ' + serviceDescriptor.path);
```

and changed the configuration to:

```javascript
app.configure(
  distribution({
    hooks: {
      before: {
        all: [authenticate('jwt')],
      },
    },
  })
);
```

now every remot service which gets registered authenticates the user on the gatway and proxies the real request to the remot service.

**Comment by claustres** [comment]
This seems to be an elegant solution, could you provide a PR with associated tests ? Thanks

**Comment by Flofie** [comment]
I can do this.
One small problem - your tests local -> remote are failing and I cant find the reason. Can you check why they are failing? I tried it with a clean clone of your repo.

**Comment by claustres** [comment]
Sorry but I can't reproduce the issue neither on travis or in my dev environment, what are the error messages ?

**Comment by Flofie** [comment]
```bash
    1) dispatch create service events from local to remote
    2) dispatch update service events from local to remote
    3) dispatch patch service events from local to remote
    4) dispatch remove service events from local to remote


  9 passing (28s)
  4 failing

  1) feathers-distributed dispatch create service events from local to remote:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) feathers-distributed dispatch update service events from local to remote:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3) feathers-distributed dispatch patch service events from local to remote:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  4) feathers-distributed dispatch remove service events from local to remote:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by claustres** [comment]
I am using 8.9.3 but travis tests also v6 and v4. Could you set the `DEBUG` environment variable to `feathers-distributed` before running the tests then send me the complete output please ?

**Comment by claustres** [comment]
A random behavior might be related to an async issue :-(

**Comment by claustres** [comment]
Fixed by https://github.com/kalisio/feathers-distributed/pull/8
