### ISSUE TITLE
npm install is not copying necessary files.

### ISSUE THREAD

**Issue by aganoop** [kalisio/feathers-distributed#41]
### Steps to reproduce
Thank you very much for the great effort to make this simple distributed micro service plug in. I would like to notice the issue in **npm** install of this package. 

I have tried both script to install the plug in.
- [ ] npm install @kalisio/feathers-distributed --save
- [ ] npm install https://github.com/kalisio/feathers-distributed --save

But I am getting the following folders/files only,
  .github
  example
  .codeclimate.yml
  Architecture Diagram.svg
  Architecture Diagram.xml
  CHANGELOG.md
  LICENSE
  package.json
  README.md

I can see lot of other files when I downloaded the complete code from git. The example also working fine in my machine. I can use the downloaded copy of files in my project but I would like to install all packages through **npm**. 

### Expected behavior
Install complete package though **npm** package manager.

### Actual behavior
Files are missing when installing though **npm**.

### System configuration

**Module versions** (especially the part that's not working): @kalisio/feathers-distributed@0.7.1

**NodeJS version**: 12.8.0

**Operating System**: Windows 10 Enterprise Edition

**Comment by claustres** [comment]
I've just tested `npm install -g @kalisio/feathers-distributed` and the installed package contains a `lib`/`node_modules` folder as expected. 

I am using node v8.16 and unfortunately we did not yet test it with Node v10/v12. Will try to add these targets in Travis and see what is going on.

**Comment by claustres** [comment]
Except some tests failing it appears to run almost fine on Node v12 as well. I've just tested local installation with `npm install @kalisio/feathers-distributed --save` and I am able to import the module.

Please note that it's normal that some files in the repo are not in the released package because they are of no use, for instance the `src`/`test` folders only used in development mode.

**Comment by aganoop** [comment]
Thanks for your feed back!
The import/require function is not working when I installed this plug in by using npm. I have tested with some other folders but I am getting the same issue. I have listed above the files what I am getting. That is the expected files list? My network also don't have any restriction. I will try with some other network too. I wonder, I am not getting this issue with any other plugins.

**Comment by aganoop** [comment]
Right now I got the lib folder and its working fine with **npm** command. I never changed the network as well as the machine. But its working for me!
Thanks for your time and effort!

**Comment by aganoop** [comment]
This is to add some additional observation that may help. The install through **npm** and import are working fine. But communication between micro-services are not working properly with **node v12**.

**Comment by claustres** [comment]
OK thanks just added https://github.com/kalisio/feathers-distributed/issues/42.
