### ISSUE TITLE
[Query] Using remote services inside local service methods

### ISSUE THREAD

**Issue by subodhpareek18** [kalisio/feathers-distributed#5]
Not sure if it already works, but would be great if something like this would continue to work. Would make splitting existing code into separate servers smooth as butter.

```js
setup(app) {
  this.remoteService = app.service('/myremoteService')  // proxies HTTP calls to that server
}

create() {
  // use this.remoteService here
}
```

Without this if we want to use a remove service we'd have to write proxy wrappers for them every where, and then the events would be duplicated, etc etc

**Comment by subodhpareek18** [comment]
Really great that you're working on this though, was really wanting something like this. Will try and contribute to this repo.

**Comment by claustres** [comment]
This should already work but because of the async behaviour of the different apps you have to listen to the  `service` event like in the tests to know when a new remote service  is available: https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js#L60.
