### ISSUE TITLE
Publishing a new NPM version

### ISSUE THREAD

**Issue by dekelev** [kalisio/feathers-distributed#52]
Hi @claustres , any chance you can publish a new version with all the changes that were already merged to the master branch?

I'm currently using the master branch directly in a forked repo and the yarn.lock file keeps changing the repo URL from SSH to HTTPS and back on it's own. not sure how to solve this beside using an NPM package.

**Comment by claustres** [comment]
Hi, we are currently working on a major architectural rewrite to get rid of the following issues: https://github.com/kalisio/feathers-distributed/issues/45 & https://github.com/kalisio/feathers-distributed/issues/48. 

If everything goes fine we should publish a new release soon, hopping no breaking changes.

**Comment by dekelev** [comment]
Got it, thanks!
