### ISSUE TITLE
Migrating multiple Feathers apps from v0.x to v1.x

### ISSUE THREAD

**Issue by dekelev** [kalisio/feathers-distributed#56]
When migrating from v0.7.1 to v1.x, is it required to deploy all the involved Feathers apps together? Will the discovery work between apps that are using v0.x and apps with v1.x?

**Comment by claustres** [comment]
Nope sorry, the underlying architecture has been almost completely updated to mainly tackle this issue https://github.com/kalisio/feathers-distributed/issues/48 but also to make it more simple, thus more reliable. 

That's the reason why we also pushed a major version update. I will update the README to state this clearly.

**Comment by claustres** [comment]
Done, any improvement in docs is welcome.
