### ISSUE TITLE
Not Working With REST API

### ISSUE THREAD

**Issue by SureDroid** [kalisio/feathers-distributed#69]
Feathers Distributed works with websockets, however when using a service on a node different from the one you are connecting, the rest api (i.e curl/fetch) doesn't work.

### Steps to reproduce
Should be self explanatory to reproduce, but here is a repo demonstrating the issue: 
https://github.com/SureDroid/feathers-distributed-rest-issue
The repo uses docker with node:12-alphine, but could also be reproduced without docker.

### Expected behavior
Feathers-distributed should work with the rest api and successfully fetch from other services.

### Actual behavior
Feathers returns an error with 404 not found.

**Comment by claustres** [comment]
For your information we have some [tests](https://github.com/kalisio/feathers-distributed/blob/master/test/index.test.js#L254) performed against a REST Feathers client which worked fine so far. Moreover [our example](https://github.com/kalisio/feathers-distributed/tree/master/example) exhibits 2 apps (a gateway + a todo service) and with POSTMAN I can make a get request with the correct authorization header on eg http://localhost:3030/todos/pDgFIW30HjTNY8GA although the service is located on http://localhost:3031.

Will try to understand the difference with your use case, maybe you can have a look to this links meanwhile in any case you find something different.

**Comment by claustres** [comment]
It appears to me your are facing this [issue](https://github.com/kalisio/feathers-distributed/issues/3), as also explained in [docs](https://github.com/kalisio/feathers-distributed#remote-services). Removing this [line](https://github.com/SureDroid/feathers-distributed-rest-issue/blob/master/gateway/src/app.ts#L50) makes it work.

Will try to make it more visible in docs.

**Comment by SureDroid** [comment]
Ah, didn't even realize the error handler was the issue. Like you said, making it more visible might help against more similar issues such as this one. Thanks and good luck!
