### ISSUE TITLE
ERROR install if npm uuid package is already a dependency

### ISSUE THREAD

**Issue by corepay** [kalisio/feathers-distributed#72]
### Steps to reproduce

1.  Fresh feathers install
2.  Add npm `uuid` package -> yarn dev server starts
3.  Add `@kalisio/feathers-distributed` -> yarn dev error below in image.
4.  remove `uuid`, `node_modules` and `yarn.lock` the rebuild dependencies -> server starts fine
5.  Add `uuid` and restart -> error below.

uuid updated their imports a couple months ago.  Looks to me like distributed feathers is trying to require `uuid` the old way on the new uuid package if it already exists node_modules.

![image](https://user-images.githubusercontent.com/48992923/87596584-5fb4ed00-c6be-11ea-935a-b1e5fe7034a5.png)

**Comment by corepay** [comment]
![image](https://user-images.githubusercontent.com/48992923/87601538-495d6000-c6c3-11ea-8aa9-1149d3ec831b.png)

**Comment by corepay** [comment]
error here `/@kalisio/feathers-distributed/lib/index.js`

common js require for v4 === `const { v4: uuidv4 } = require('uuid');`

![image](https://user-images.githubusercontent.com/48992923/87601706-9e00db00-c6c3-11ea-8085-ed416dfcd52e.png)

**Comment by corepay** [comment]
server starts if I make the following change but not sure yet if this is going to jack anything else up in your package.  

![image](https://user-images.githubusercontent.com/48992923/87604039-3c8e3b80-c6c6-11ea-9c76-4c364815e15e.png)

**Comment by corepay** [comment]
nope -> now looking for v2 uuid.  I'll wait for you to take a look and straighten out the uuid dependencies...over my head already.

![image](https://user-images.githubusercontent.com/48992923/87605615-1a48ed80-c6c7-11ea-9a98-beaf145c7545.png)

**Comment by corepay** [comment]
I removed the `uuid` and replaced with [uuid-random](https://www.npmjs.com/package/uuid-random) in my project.  all looks good now.  uuid-random looks to be a lot faster than uuid and has the same syntax you are using now without requiring a module like uuid does now.  Could be a good, quick replacement for uuid your library.

![image](https://user-images.githubusercontent.com/48992923/87607627-c4c30f80-c6cb-11ea-8228-cdfee00b1a3f.png)

**Comment by claustres** [comment]
It seems to me that you are creating a version conflict by adding the `uuid` package in a different version than we are using. As they changed the interface (breaking change) you need to stick to our version if you don't want things to break. I guess that running `yarn add uuid@3.2.1` (version of our lock file) or using a [resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) should fix it.

Anyway, I can we can also easily upgrade the uuid package to e newer version, it's only used when initializing an app to get a unique ID, we don't have any performance issue here.
