### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by THEJean-Kevin** [kalisio/feathers-distributed#74]
Bonjour,

J'ai 2 applications feathers (A et B).
J'ai l'application A qui doit effectuer un find sur un service de l'application B or j'ai a chaque fois l'erreur "Cannot read property 'find' of undefined".

Après plusieurs recherches. J'ai remarqué que l'erreur apparaissait quand 
- L'application B démarrais avant l'application A
- Lancement des applications A puis B (aucune erreur). Mais si A admettais a restart l'erreur survient.

Cela pose un problème lors du deuxième cas car mes applications son sous pm2 (donc l'autorestart en cas de probleme).
Y a t'il une configuration que j'ai mal faite?

config A
app.configure(distribution({
  key: 'charactercreator',
  remoteServices: ['componentInventory']
}));

config B
app.configure(distribution({
  key: 'inventory',
  services: ['componentInventory']
}));

**Comment by claustres** [comment]
Bonjour, d'après l'erreur il semble que le remote service n'a pas été instancié sur l'application B. Soit B ne "voit" pas l'application A soit la déclaration du service n'a pas été correctement reçue/faite. Vous pouvez activer les logs de debug pour avoir plus d'info en définissant la variable d’environnement suivante: `DEBUG=feathers-distributed*`.

En général cela se produit lorsque deux applications se lancent à peu près simultanément. En effet l'initialisation des composants sous-jacents est asynchrone et il n'y a pas vraiment de barrière de synchronisation possible. Aussi si les événements de publication d'une app et/ou de ses services a lieu pendant que l'autre application s'initialise ils peuvent être perdus.

La solution de contournement standard consiste à lancer les applications de façon "plus déterministe" en laissant le temps à la première de s'initialiser avant de lancer la seconde. Il y a aussi [deux options](https://github.com/kalisio/feathers-distributed#initialization) permettant de paramétrer le délai avant l'initialisation du module ou la publication des services afin de "décaler" l'initialisation des deux applications.

En espérant que cela résoudra votre problème.
