### ISSUE TITLE
Add healthcheck endpoint(s)

### ISSUE THREAD

**Issue by claustres** [kalisio/feathers-distributed#79]
It is often useful to be able to check if remote apps are correctly reachable from an external point of view eg healthcheck monitoring. Indeed each app can be "healthy" but the communication between both can be broken.

We should provide a endpoint allowing to check if a given app is correctly registered/reachable from another one. As apps are uniquely identified using their partition key we should generate endpoints using the following pattern `/distribution/healthcheck/:key`.  HTTP `GET` operation on this endpoint could trigger a get operation on an in-memory service of the remote app to ensure communication works fine.

**Comment by bmbariah** [comment]
Looking forward to this feature

**Comment by claustres** [comment]
We also need it for production use, it should come soon.

**Comment by claustres** [comment]
By the way @bmbariah what is your use case with this module ?
